### PR TITLE
searching for the public key is now case insensitive.

### PR DESCRIPTION
**Pull request by mgrossmann**
it would be nice to ignore the case while searching for keyrings

ps. my code changes belong to the same license like the original code.

### CODE REVIEW

**Comment by neuhalje** [comment]
Hi Mike,

thanks for the PR!

I tested with several versions of gpg2 and cases insensitive is indeed the default behaviour.

Two minor issues:
* Please also make sure that `extractSecretSigningKeyFromKeyrings` and `extractPublicKeyRingForUserId` behave alike (your patch introduces a diverging behaviour).
* Would you mind to add matching unit tests?

**Comment by mgrossmann** [comment]
Hi Jens,

i will fix both isues.

/mig

**Comment by neuhalje** [comment]
ping :-)

**Comment by mgrossmann** [comment]
I am currently on vacation. Then I will take care of the case.

**Comment by neuhalje** [comment]
Enjoy your vacation! I did some (minor) refactorings, please don't forget to pull before continuing on the code

**Comment by mgrossmann** [comment]
I'm still alive. :) I have fixed your first request. I will try to implement the tests this week.

**Comment by neuhalje** [comment]
Hi @mgrossmann, my reformatting of the source code made this merge very, very messy. The easiest way would be for you to check out the current master and manually re-apply your commit 477c7c0d1a4edfe66dbecc43e11d28e72836dbb7:

```diff
--- a/src/main/java/name/neuhalfen/projects/crypto/bouncycastle/openpgp/keys/PGPUtilities.java
+++ b/src/main/java/name/neuhalfen/projects/crypto/bouncycastle/openpgp/keys/PGPUtilities.java
@@ -80,8 +80,9 @@ public final class PGPUtilities {
             throw new NullPointerException("publicKeyRings must not be null");
         }

-        // the true parameter indicates, that partial matching of the publicKeyUid is enough.
-        final Iterator<?> keyRings = publicKeyRings.getKeyRings("<" + publicKeyUid + ">", true);
+        // the first true parameter indicates, that partial matching of the publicKeyUid is enough.
+        // the second true parameter indicates, that matching the publicKeyUid is case insensitive.
+        final Iterator<?> keyRings = publicKeyRings.getKeyRings("<" + publicKeyUid + ">", true, true);
         PGPPublicKeyRing returnKeyRing = null;
         while (keyRings.hasNext()) {
             final Object currentKeyRing = keyRings.next();
```

Sorry for the inconvenience

**Comment by neuhalje** [comment]
Hi, any progress on the test? Cheers!

**Comment by mgrossmann** [comment]
Gesundes neues Jahr.

Leider noch nicht, aber die guten Vorsätze beinhalten auch die Tests.

VG

**Comment by neuhalje** [comment]
Implemented in [Rfc4880KeySelectionStrategy](https://github.com/neuhalje/bouncy-gpg/blob/master/src/main/java/name/neuhalfen/projects/crypto/bouncycastle/openpgp/keys/callbacks/Rfc4880KeySelectionStrategy.java)

**Pull request closed without merging**
