### PR TITLE
Added the MDC verification code

### PR DESCRIPTION
**Pull request by Sauhardstark**
- Created a wrapping MDC validating stream
- It confirms data integrity if MDC packet is present
- Added a test case to confirm exception if data is violated

### CODE REVIEW

**Comment by Sauhardstark** [comment]
Addresses the issue #45

**Comment by Sauhardstark** [comment]
@neuhalje Can you please rake a look

**Comment by neuhalje** [comment]
At a first glance this looks good. In the Test we should comment where the magic 595 came from.

I suggest that you comment that and squash the commit. I’ll be back to the keyboard this evening.

I was thinking of rewriting the two stream wrappers with an observable stream and two listeners for the close event as a next step. What is your opinion on that?

Slightly unrelated: Also I am planning to switch from throwing IOEcxeptions to introducing some kind of „Logging“ object where we can protocol e.g. the signatures checked, the keys used and the errors encountered.  How does that sound?

**Comment by Sauhardstark** [comment]
@neuhalje 
I'll write the comments regarding the 595 bit
The stream wrapper to observable stream sounds great as that will be easier to scale if new changes come.
Regarding the Logging object, I'm not sure I entirely understand what the proposed change is (like is the Logging object a custom POJO that contains placeholders for data, exceptions etc ?)

**Comment by Sauhardstark** [comment]
@neuhalje any updates on the above please ?

**Comment by neuhalje** [comment]
My bad - I did not see your latest commit! This afternoon I'll merge and also look a the others. Thank you very much, If you'd like to, we can tackle a few other things as well

**Comment by Sauhardstark** [comment]
I've sent you a mail regarding discussing other topics

**Pull request merged**
